---



- name: Include roles for playbook operations
  hosts: all
  tasks:

    - name: Include downstream tasks within roles
      ansible.builtin.include_role:
        name: enasisnetwork.provision.default
        tasks_from: params
      vars:
        provision_kind: virtual
        provision_family: almalinux
        provision_stage: /dev/null

    - name: Include downstream tasks within roles
      ansible.builtin.include_role:
        name: enasisnetwork.provision.default
        tasks_from: overview
