---



- name: Include roles for playbook operations
  hosts: all
  tasks:

    - name: Include downstream tasks within roles
      ansible.builtin.include_role:
        name: enasisnetwork.provision.default
        tasks_from: params

    - name: Include downstream tasks within roles
      ansible.builtin.include_role:
        name: enasisnetwork.provision.default
        tasks_from: facts

    - name: Include downstream tasks within roles
      ansible.builtin.include_role:
        name: enasisnetwork.provision.default
        tasks_from: overview
