---



dependency:
  name: galaxy
  options:
    requirements-file: require.yml

driver:
  name: docker

platforms:
  - name: enasprv1
    image: almalinux:9
    pre_build_image: true
    privileged: true

provisioner:
  name: ansible
  options:
    diff: true
    v: true
  config_options:
    ssh_connection:
      pipelining: true
  playbooks:
    converge: converge.yml
