---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Assert conditions for downstream tasks

  ansible.builtin.assert:
    that:

      - >-  # always in serial mode
        ansible_play_batch | length == 1

  tags: always






- name: Mount the source installation image

  mountiso:
    src: '{{ _prvinstall_source }}'
    dest: '{{ _prvinstall_distrib }}'
    state: present

  delegate_to: localhost

  when: provision_install | default

  tags: always
