---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Declare relevant playbook variables

  ansible.builtin.set_fact:

    _provision_download: >-
      {%- set path = install.source -%}
      {{- path
          if path and path[:4] == 'http'
          else none -}}
    _provision_install_base: >-
      {{- '%s/%s' | format(staging, install.cached)
          if install.cached else install.source -}}
    _provision_install_hash: >-
      {{ install.checksum | default }}

    _provision_distrib_path: >-
      {{ staging }}/{{ family }}-dist
    _provision_prepare_path: >-
      {{ staging }}/{{ family }}-prep

    _provision_install_path: >-
      {{ staging }}/{{ hostname }}-install.iso
    _provision_install_unattend: >-
      {{ staging }}/{{ hostname }}-unattend
    _provision_install_unscript: >-
      {{ staging }}/{{ hostname }}-unscript

  vars:
    hostname: '{{ inventory_hostname }}'
    family: '{{ provision_family }}'
    staging: '{{ provision_staging }}'
    install: '{{ provision_install }}'

  when: provision_install | default

  tags: always
