---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Assert conditions for downstream tasks

  ansible.builtin.assert:
    that:

      - >-  # tags are present
        'all' not in ansible_run_tags

      - >-  # only specific hosts
        'enasisnetwork_provision' in groups

  tags: always



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    params.yml

  tags: always



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    common.yml

  tags: always






# Remember basic molecule tests when updating






- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    overview.yml

  tags: overview
