---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Declare relevant playbook variables
  # Important force parsing with Jinja2
  # NOTE Remember to update the README file

  ansible.builtin.set_fact:

    provision_name: >-
      {{ provision_name | default(omit) }}
    provision_kind: >-
      {{ provision_kind | default(omit) }}
    provision_family: >-
      {{ provision_family | default(omit) }}
    provision_domain: >-
      {{ provision_domain | default(omit) }}
    provision_stage: >-
      {{ provision_stage | default(omit) }}

    provision_install: >-
      {{ provision_install | default(omit) }}
    provision_install_source: >-
      {{ provision_install_source | default(omit) }}
    provision_install_checksum: >-
      {{ provision_install_checksum | default(omit) }}
    provision_install_cached: >-
      {{ provision_install_cached | default(omit) }}

    provision_users: >-
      {{ provision_users | default(omit) }}
    provision_groups: >-
      {{ provision_groups | default(omit) }}
    provision_storage: >-
      {{ provision_storage | default(omit) }}
    provision_network: >-
      {{ provision_network | default(omit) }}

    provision_libvirt: >-
      {{ provision_libvirt | default(omit) }}
    provision_libvirt_enable: >-
      {{ provision_libvirt_enable | default(omit) }}
    provision_libvirt_autostart: >-
      {{ provision_libvirt_autostart | default(omit) }}
    provision_libvirt_host: >-
      {{ provision_libvirt_host | default(omit) }}
    provision_libvirt_prefix: >-
      {{ provision_libvirt_prefix | default(omit) }}
    provision_libvirt_vcpus: >-
      {{ provision_libvirt_vcpus | default(omit) }}
    provision_libvirt_memory: >-
      {{ provision_libvirt_memory | default(omit) }}
    provision_libvirt_uefi: >-
      {{ provision_libvirt_uefi | default(omit) }}
    provision_libvirt_osid: >-
      {{ provision_libvirt_osid | default(omit) }}
    provision_libvirt_isos: >-
      {{ provision_libvirt_isos | default(omit) }}
    provision_libvirt_install: >-
      {{ provision_libvirt_install | default(omit) }}

    provision_proxmox: >-
      {{ provision_proxmox | default(omit) }}
    provision_proxmox_enable: >-
      {{ provision_proxmox_enable | default(omit) }}
    provision_proxmox_autostart: >-
      {{ provision_proxmox_autostart | default(omit) }}
    provision_proxmox_host: >-
      {{ provision_proxmox_host | default(omit) }}
    provision_proxmox_endpoint: >-
      {{ provision_proxmox_endpoint | default(omit) }}
    provision_proxmox_port: >-
      {{ provision_proxmox_port | default(omit) }}
    provision_proxmox_username: >-
      {{ provision_proxmox_username | default(omit) }}
    provision_proxmox_password: >-
      {{ provision_proxmox_password | default(omit) }}
    provision_proxmox_token: >-
      {{ provision_proxmox_token | default(omit) }}
    provision_proxmox_secret: >-
      {{ provision_proxmox_secret | default(omit) }}
    provision_proxmox_cores: >-
      {{ provision_proxmox_cores | default(omit) }}
    provision_proxmox_memory: >-
      {{ provision_proxmox_memory | default(omit) }}
    provision_proxmox_uefi: >-
      {{ provision_proxmox_uefi | default(omit) }}
    provision_proxmox_ostype: >-
      {{ provision_proxmox_ostype | default(omit) }}
    provision_proxmox_install: >-
      {{ provision_proxmox_install | default(omit) }}

  tags: always






- name: Validate role variables using Pydantic

  enasisnetwork.provision.params:
    prefix: provision_

  register: pbvalidate

  tags: always






- name: Declare relevant playbook variables
  # Required to retain child null value

  ansible.builtin.set_fact:

    provision_name: >-
      {{ pbvalidate.params.name }}
    provision_kind: >-
      {{ pbvalidate.params.kind }}
    provision_family: >-
      {{ pbvalidate.params.family }}
    provision_domain: >-
      {{ pbvalidate.params.domain }}
    provision_stage: >-
      {{ pbvalidate.params.stage }}
    provision_install: >-
      {{ pbvalidate.params.install }}
    provision_users: >-
      {{ pbvalidate.params.users }}
    provision_groups: >-
      {{ pbvalidate.params.groups }}
    provision_storage: >-
      {{ pbvalidate.params.storage }}
    provision_network: >-
      {{ pbvalidate.params.network }}
    provision_libvirt: >-
      {{ pbvalidate.params.libvirt }}
    provision_proxmox: >-
      {{ pbvalidate.params.proxmox }}

  tags: always
