---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Upload the installation to hypervisor

  ansible.builtin.copy:
    src: '{{ _prvinstall_output }}'
    dest: '{{ _prvlibvirt_install }}'
    mode: '0644'

  when:
    - provision_install
    - provision_libvirt.enable

  delegate_to: '{{ provision_libvirt.host }}'
  throttle: 1

  tags: always
