---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Assert conditions for downstream tasks

  ansible.builtin.assert:
    that:

      - >-  # tags are present
        'all' not in ansible_run_tags

      - >-  # only specific hosts
        'enasisnetwork_provision' in groups

  tags: always



- name: Include downstream tasks within roles

  ansible.builtin.include_role:
    name: enasisnetwork.provision.default
    tasks_from: params

  tags: always



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    facts.yml

  when:
    - provision_proxmox | default
    - provision_proxmox.endpoint

  tags: always






# Remember basic molecule tests when updating






- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    create.yml

  when:
    - provision_proxmox | default
    - provision_proxmox.endpoint

  tags: proxmox-create



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    update.yml

  when:
    - provision_proxmox | default
    - provision_proxmox.endpoint

  tags: proxmox-update



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    install/upload.yml

  when:
    - provision_proxmox | default
    - provision_proxmox.endpoint

  tags: proxmox-install-upload



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    install/delete.yml

  when:
    - provision_proxmox | default
    - provision_proxmox.endpoint

  tags: proxmox-install-delete



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    poweron.yml

  when:
    - provision_proxmox | default
    - provision_proxmox.endpoint

  tags: proxmox-poweron



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    nopower.yml

  when:
    - provision_proxmox | default
    - provision_proxmox.endpoint

  tags: proxmox-nopower



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    delete.yml

  when:
    - provision_proxmox | default
    - provision_proxmox.endpoint

  tags: proxmox-delete






- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    overview.yml

  when:
    - provision_proxmox | default
    - provision_proxmox.endpoint

  tags: proxmox-overview
