---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Delete the installation on hypervisor

  ansible.builtin.file:
    path: '{{ _prvproxmox_install }}'
    state: absent

  when:
    - provision_install
    - provision_proxmox.enable

  delegate_to: '{{ provision_proxmox.host }}'
  throttle: 1

  tags: always
