---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Download the ISO from configured source

  ansible.builtin.get_url:
    url: '{{ _prvinstall_download }}'
    dest: '{{ _prvinstall_source }}'
    checksum: '{{ _prvinstall_srchash }}'
    mode: '0644'

  delegate_to: localhost
  throttle: 1

  when: _prvinstall_download

  tags: always
