---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Assert conditions for downstream tasks

  ansible.builtin.assert:
    that:

      - >-  # tags are present
        'all' not in ansible_run_tags

      - >-  # only specific hosts
        'enasisnetwork_provision' in groups

  tags: always



- name: Include downstream tasks within roles

  ansible.builtin.include_role:
    name: enasisnetwork.provision.default
    tasks_from: params

  tags: always






# Remember basic molecule tests when updating






- name: Assert conditions for downstream tasks

  ansible.builtin.assert:
    that:
      - _prvinstall_source

  when: provision_install | default

  tags: always






- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    download.yml

  tags:
    - install-download
    - install-prepare
    - install-build



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    prepare.yml

  tags:
    - install-prepare
    - install-build



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    unattend.yml

  tags:
    - install-unattend
    - install-build



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    build.yml

  tags: install-build



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    delete.yml

  tags:
    - install-delete
    - install-clean



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    clean.yml

  tags: install-clean
