---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Assert conditions for downstream tasks

  ansible.builtin.assert:
    that:

      - >-  # always in serial mode
        ansible_play_batch | length == 1

  tags: always






- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    mount/absent.yml

  tags: always



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    folders.yml

  tags: always



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    mount/present.yml

  tags: always



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    rsync.yml

  tags: always



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    updates.yml

  tags: always



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    mount/absent.yml

  tags: always
