---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Declare the initial values for guest

  ansible.builtin.set_fact:

    _prvlibvirt_name: >-
      {{ inventory_hostname }}
    _prvlibvirt_uuid: >-
      {{ inventory_hostname | to_uuid }}

    _prvinstall_output: >-
      {%- if not provision_libvirt.install -%}
      {{-   stage }}/{{ hostname }}-install.iso
      {%- else -%}
      {{-   provision_libvirt.install -}}
      {%- endif -%}

  vars:
    hostname: '{{ inventory_hostname }}'
    stage: '{{ provision_stage }}'

  when: provision_libvirt.host

  tags: always






- name: Retrieve the current list of guests

  community.libvirt.virt:
    command: info
    uri: '{{ provision_libvirt.prefix }}/system'

  register: _prvlibvirt_guests

  delegate_to: '{{ provision_libvirt.host }}'
  check_mode: false
  changed_when: false

  when: provision_libvirt.host

  tags: always



- name: Structure the current list of guests

  ansible.builtin.set_fact:

    _prvlibvirt_guests: '{{ guests }}'
    _prvlibvirt_guest: >-
      {%- set name = _prvlibvirt_name -%}
      {%- if name in guests -%}
      {{-   guests[name] -}}
      {%- endif -%}

  vars:
    guests: >-
      {%- set guests = {} -%}
      {%- set items = (
            _prvlibvirt_guests
            .items()) -%}
      {%- for name, item in items
           if item is not boolean -%}
      {%-   set update = {name: item} -%}
      {%-   do guests.update(update) -%}
      {%- endfor -%}
      {{- guests -}}

  when:
    - provision_libvirt.host

  tags: always






- name: Retrieve the storage pool information

  community.libvirt.virt_pool:
    command: info
    uri: '{{ provision_libvirt.prefix }}/system'

  register: _prvlibvirt_stores

  delegate_to: '{{ provision_libvirt.host }}'
  check_mode: false
  changed_when: false

  when: provision_libvirt.host

  tags: always



- name: Force refresh storage pool information

  community.libvirt.virt_pool:
    command: refresh
    name: '{{ item }}'
    uri: '{{ provision_libvirt.prefix }}/system'

  loop: '{{ _prvlibvirt_stores.pools | list }}'

  delegate_to: '{{ provision_libvirt.host }}'
  check_mode: false
  changed_when: false

  when: provision_libvirt.host

  tags: always



- name: Retrieve the storage pool information

  community.libvirt.virt_pool:
    command: info
    uri: '{{ provision_libvirt.prefix }}/system'

  register: _prvlibvirt_stores

  delegate_to: '{{ provision_libvirt.host }}'
  check_mode: false
  changed_when: false

  when: provision_libvirt.host

  tags: always



- name: Structure the storage pool information

  ansible.builtin.set_fact:

    _prvlibvirt_stores: >-
      {{ _prvlibvirt_stores.pools }}

  when: provision_libvirt.host

  tags: always






- name: Define the filesystem path to the ISO

  ansible.builtin.set_fact:
    _prvlibvirt_install: >-
      {%- set stores = _prvlibvirt_stores -%}
      {%- set store = provision_libvirt.isos -%}
      {%- set path = stores[store].path -%}
      {{ path }}/{{ _prvlibvirt_name }}.iso

  when:
    - provision_install
    - provision_libvirt.host

  tags: always



- name: Assert conditions for downstream tasks

  ansible.builtin.assert:
    that:

      - >-  # libvirt module issue
        _prvlibvirt_name not in [
          'changed', 'failed']

  tags: always






- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    install/present.yml

  tags: always






- name: Define the parameters for the guest

  ansible.builtin.set_fact:

    _prvlibvirt_params: >-
      {{ lookup('template', 'guest.j2') }}

  when: provision_libvirt.host

  tags: always
