---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Declare relevant playbook variables

  ansible.builtin.set_fact:
    _provision_params: >-
      {{ lookup('template', 'guest.j2') }}

  tags: always



- name: Include downstream tasks within roles

  ansible.builtin.include_role:
    name: enasisnetwork.provision.default
    tasks_from: overview

  tags: always
