---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Include downstream tasks within roles

  ansible.builtin.include_role:
    name: enasisnetwork.provision.default
    tasks_from: overview

  tags: always
