---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Update the guest within the hypervisor

  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'guest.j2') }}"
    uri: '{{ provision_libvirt.prefix }}/system'

  delegate_to: '{{ provision_libvirt.host }}'
  changed_when: true

  when:
    - provision_libvirt.host
    - _prvlibvirt_guest
    - not ansible_check_mode

  tags: always



- name: Update the guest within the hypervisor

  ansible.builtin.command: /bin/true

  delegate_to: '{{ provision_libvirt.host }}'
  changed_when: _prvlibvirt_guest
  check_mode: false

  when:
    - provision_libvirt.host
    - ansible_check_mode
      or not _prvlibvirt_guest

  tags: always
